export const profile = {
  name: "Karan Gupta",
  email: "k79gupta@uwaterloo.ca",
  location: "San Francisco, CA",
  education: "Computer Engineering",
  university: "University of Waterloo",
  minor: "Economics minor",
  gpa: "3.95",
  resume: "/KaranGuptaResume.pdf",
  resumeUpdated: "2026-10-06",
  links: {
    github: "https://github.com/Karan-Gupta07",
    linkedin: "https://www.linkedin.com/in/karan-gupta-2b72a735a/",
    letterboxd: "https://letterboxd.com/Exoxeon/",
    music: "https://www.albumoftheyear.org/user/exoxoen/",
  },
};

export const projects = [
  {
    slug: "dominiq",
    links: { github: "https://github.com/savirsingh/DominIQ", devpost: "https://devpost.com/software/dominiq" },
    video: "zN7Yl_UZopU",
    code: "PRJ–06",
    title: "DominIQ",
    category: "ROBOTICS & AUTONOMY",
    short: "Multi-asset mission control with a spatial Quest interface.",
    stack: [
      "Python",
      "PyMAVLink",
      "YOLOv8",
      "ArduPilot",
      "OpenCV",
      "WebXR",
      "TypeScript",
    ],
    summary:
      "A concurrent MAVLink mission controller coordinating four autonomous assets, with visual target localization and a Meta Quest 3 interface. Built at Hack The North 2026.",
    paragraphs: [
      "Coordinated four heterogeneous autonomous assets through a concurrent MAVLink mission controller with dynamic search, interception, target confirmation, tracking, and lost-target recovery.",
      "Achieved 98% vessel detection accuracy by fine-tuning YOLO26m and fusing camera detections with robot altitude, orientation, and camera geometry to localize targets in a shared coordinate system without relying on GPS.",
      "Built a Meta Quest 3 interface using WebXR and Meta IWSDK to display telemetry, camera feeds, and targets in 3D. DominIQ was a Hack The North 2026 winner.",
    ],
    distinction: "WINNER / HACK THE NORTH 2026",
    metrics: [
      { value: "4", label: "Autonomous assets coordinated" },
      { value: "98%", label: "Vessel detection accuracy" },
    ],
    flow: [
      "ASSET TELEMETRY",
      "TARGET DETECTION",
      "MISSION CONTROL",
      "QUEST INTERFACE",
    ],
    flowLabels: [
      "Pose + camera feeds",
      "YOLO + shared coordinates",
      "Concurrent MAVLink missions",
      "WebXR + Meta IWSDK",
    ],
  },
  {
    slug: "mr-clean",
    links: { github: "https://github.com/Karan-Gupta07/Mr.-Clean-Bracketbot-Cleaning-Robot", devpost: "https://devpost.com/software/mr-clean" },
    video: "WjJpOjjXQZs",
    code: "PRJ–07",
    title: "Mr. Clean",
    category: "ROBOT LEARNING",
    short: "Navigation and object pickup with learned manipulation.",
    stack: [
      "Python",
      "PyTorch",
      "MuJoCo",
      "ROS 2",
      "OpenCV",
      "Stable-Baselines3",
      "Docker",
    ],
    summary:
      "A robotics system combining collision-free navigation, reinforcement-learning object pickup, and multi-camera manipulation trajectories.",
    paragraphs: [
      "Built an A* planner with obstacle inflation, spline trajectories, LiDAR and odometry, and closed-loop control. Achieved nine out of nine collision-free navigation routes with zero falls and docking error below 10 cm and 5°.",
      "Trained a reinforcement-learning policy in MuJoCo for household objects, achieving 95% pickup success.",
      "Implemented an Action Chunking Transformer that fuses three camera streams with robot state through ResNet-18, a CVAE encoder, and a transformer to generate 32-step manipulation trajectories.",
    ],
    distinction: "NAVIGATION / REINFORCEMENT LEARNING / MANIPULATION",
    metrics: [
      { value: "9/9", label: "Collision-free navigation routes" },
      { value: "95%", label: "Object pickup success" },
    ],
    flow: ["PERCEPTION", "NAVIGATION", "MANIPULATION"],
    flowLabels: [
      "LiDAR, odometry + three cameras",
      "A*, spline paths + docking",
      "RL pickup + 32-step ACT",
    ],
  },
  {
    slug: "reparo",
    links: { github: "https://github.com/Karan-Gupta07/RepairBOT" },
    video: "JoFuqZbOmnA",
    code: "PRJ–01",
    title: "Reparo",
    category: "AGENTIC SYSTEMS",
    short: "Repair plans and parts sourcing with Gemini.",
    stack: ["Python", "Gemini API", "React", "Node.js", "Swift", "PyTorch"],
    summary:
      "An agentic AI repair platform that turns a product image into a repair plan, a parts list, and a path back to working order.",
    paragraphs: [
      "Built an agentic AI repair platform that uses Gemini vision models to classify products and assess repairability with over 90% accuracy, then generates step-by-step repair plans, required tools, and cost estimates.",
      "Integrated the Shopify Storefront API and SerpAPI to automate part matching and streamline the repair-to-checkout flow, reducing search time for replacement parts by 70% with access to over 1,000 real-time listings.",
      "Won 1st place in the Reactiv Track ($5,000) at Hack Canada 2026, and was shortlisted for the Most Complex AI Hack award.",
    ],
    distinction: "1ST PLACE / HACK CANADA 2026",
    metrics: [
      { value: "90%+", label: "Assessment accuracy" },
      { value: "70%", label: "Less search time" },
      { value: "1,000+", label: "Real-time listings" },
    ],
    flow: ["PRODUCT IMAGE", "GEMINI VISION", "REPAIR PLAN", "PART SOURCING"],
    flowLabels: [
      "Photo of the product",
      "Repairability assessment",
      "Steps, tools, and cost",
      "Shopify + SerpAPI",
    ],
  },
  {
    slug: "deliriumwatch",
    code: "PRJ–02",
    title: "DeliriumWatch",
    category: "COMPUTER VISION",
    short: "Patient and environmental monitoring prototype.",
    stack: [
      "Raspberry Pi",
      "Arduino",
      "Python",
      "TensorFlow",
      "scikit-learn",
      "OpenCV",
      "Flask",
      "C/C++",
      "HTML",
      "CSS",
    ],
    summary:
      "A real-time environmental and patient monitoring system designed for Grand River Hospital staff, validated through simulated testing.",
    paragraphs: [
      "Built a real-time Python monitoring pipeline with SQL-backed secure login and role-based access control for hospital staff. During simulated testing, the system reduced manual environmental monitoring by over 90%.",
      "Implemented continuous OpenCV eye detection and a custom TensorFlow and scikit-learn model for automated sleep and blink classification. A live Flask dashboard surfaced abnormal conditions through automatic alert flagging, reducing response time by 40% during validation.",
      "Engineered serial data ingestion and threshold validation for stable multi-sensor tracking with zero dropped readings during testing.",
    ],
    distinction: "HEALTHCARE / SIMULATED VALIDATION",
    metrics: [
      { value: "90%+", label: "Less manual monitoring" },
      { value: "40%", label: "Faster test response" },
      { value: "0", label: "Dropped test readings" },
    ],
    flow: ["SENSOR + VIDEO", "CV CLASSIFICATION", "STAFF DASHBOARD"],
    flowLabels: [
      "Serial ingestion",
      "Eye + sleep detection",
      "Flagged conditions",
    ],
  },
  {
    slug: "ai-admissions",
    links: { live: "https://college-results-bot.vercel.app", github: "https://github.com/Karan-Gupta07/CollegeResultsBOT" },
    code: "PRJ–03",
    title: "AI Admissions",
    fullTitle: "AI Admissions Similarity Tool",
    category: "DATA INTELLIGENCE",
    short: "Admissions benchmarking from GPA, tests, and interests.",
    stack: ["Python", "PRAW", "MongoDB"],
    summary:
      "An AI-driven admissions benchmarking tool that compares applicant profiles across GPA, test scores, and interests.",
    paragraphs: [
      "Built a tool to scrape admissions data and compute similarity scores across GPA, test results, and interests.",
      "Implemented applicant benchmarking with reach, target, and safety school classification, using Python, PRAW, and MongoDB.",
    ],
    distinction: "APPLICANT BENCHMARKING",
    metrics: [],
    flow: ["ADMISSIONS DATA", "SIMILARITY SCORE", "SCHOOL BENCHMARK"],
    flowLabels: [
      "PRAW ingestion",
      "GPA · tests · interests",
      "Reach · target · safety",
    ],
  },
  {
    slug: "silhouette",
    code: "PRJ–04",
    title: "TailorAI",
    fullTitle: "TailorAI (Silhouette)",
    category: "APPLIED MACHINE LEARNING",
    short: "Body measurements and custom apparel ordering from photos.",
    stack: [
      "Python",
      "TensorFlow",
      "scikit-learn",
      "OpenCV",
      "Node.js",
      "React",
      "MongoDB",
    ],
    summary:
      "A full-stack AI tailoring platform that extracts body measurements from photos and connects them to a custom apparel catalog.",
    paragraphs: [
      "Built a full-stack AI-powered custom tailoring platform using computer vision and the MERN stack, processing over 200 images to automatically extract more than 10 body measurements per user.",
      "Implemented a Python computer vision workflow with landmark normalization, using scikit-learn and TensorFlow to improve measurement consistency by 40%.",
      "Designed a scalable MongoDB schema and optimized REST APIs supporting over 150 catalog items, with query latency below 200 milliseconds. Built the responsive React frontend for the complete ordering experience.",
    ],
    distinction: "SILHOUETTE / FULL-STACK PLATFORM",
    metrics: [
      { value: "10+", label: "Body measurements" },
      { value: "40%", label: "More consistent" },
      { value: "<200ms", label: "Catalog query latency" },
    ],
    flow: ["USER PHOTOS", "CV LANDMARKS", "CUSTOM APPAREL"],
    flowLabels: [
      "Image input",
      "Normalized measurements",
      "Catalog + ordering",
    ],
  },
  {
    slug: "spotify-pi",
    links: { github: "https://github.com/Karan-Gupta07/SpotifyPiThing" },
    code: "PRJ–05",
    title: "Spotify Pi Thing",
    category: "EMBEDDED SYSTEMS",
    short: "A touchscreen Spotify controller for Raspberry Pi.",
    stack: [
      "Raspberry Pi",
      "Python",
      "FastAPI",
      "Spotipy",
      "HTML",
      "CSS",
      "JavaScript",
    ],
    summary:
      "A standalone Raspberry Pi Spotify controller with a touch-optimized interface, persistent authentication, and automatic kiosk startup.",
    paragraphs: [
      "Built a standalone Raspberry Pi Spotify controller that acts like a small in-car console. Everything runs locally on the device, with a touch-optimized interface in a fullscreen browser.",
      "The Python backend uses FastAPI and Spotipy to serve a REST API and handle Spotify OAuth. Persistent token caching allows the device to reconnect independently after a reboot.",
      "The vanilla HTML, CSS, and JavaScript frontend is designed for 3.5–5 inch touchscreens and polls the backend every three seconds for playback updates. Automated systemd deployment scripts start the backend at boot, then launch Chromium in kiosk mode.",
    ],
    distinction: "HARDWARE / LOCAL-FIRST INTERFACE",
    metrics: [
      { value: "3s", label: "Playback refresh" },
      { value: "3.5–5″", label: "Touchscreen size" },
    ],
    flow: ["SPOTIFY API", "FASTAPI + SPOTIPY", "TOUCH DISPLAY"],
    flowLabels: ["OAuth + playback", "Raspberry Pi backend", "Chromium kiosk"],
  },
];

export const experience = [
  {
    slug: "overlap",
    company: "Overlap",
    role: "Software Engineering Intern",
    date: "Sep 2026 — Present",
    current: true,
    location: "San Francisco, CA",
    field: "YC S24 / AI VIDEO SYSTEMS",
    intro: "At Overlap, I work on the systems that turn hours-long videos into short clips. This demo shows one idea behind that: spend the analysis budget where the action is.",
    bullets: [
      "Increased customer engagement by 15% by building a PyTorch trend-forecasting model using 20+ customer, content, engagement, and external signals to guide video topics, editing styles, and publishing timing.",
      "Built a file-size-capped 4 FPS video proxy with motion-adaptive Gemini frame sampling, speeding up scene detection 1.6–2.4× and enabling AI clip generation on long-form videos spanning two to seven hours.",
    ],
  },
  {
    slug: "amazon",
    company: "Amazon",
    role: "Software Development Engineer Intern",
    date: "May 2026 — Aug 2026",
    location: "Toronto, ON",
    field: "AUTOMATION / DISTRIBUTED SYSTEMS",
    intro: "At Amazon, I helped create a route-planning optimization algorithm now deployed in every Amazon fulfillment center worldwide. This demo illustrates the idea: collect the same items with less travel.",
    bullets: [
      "Decomposed a 9,400-line warehouse decision engine into pluggable microservices, enabling dynamic selection of item-picking optimization algorithms deployed across every fulfillment center.",
      "Reduced legacy service migration time by 98% (two weeks to two hours) by building an agentic AI migration system with autonomous architecture discovery and 20 reusable deterministic transformation skills.",
      "Re-architected the execution engine across ECS, Lambda, Step Functions, and S3, eliminating redundant computation in algorithm selection and reducing end-to-end execution time from 16 seconds to 4.5 seconds.",
      "Built a semantic-diff validation harness to replay production JSON payloads against generated endpoints, evaluating behavioral parity via a confidence metric that flags inconclusive noise across 42 execution paths.",
    ],
  },
  {
    slug: "wat-ai",
    company: "Wat.ai",
    role: "AI Software Engineer, Evaluation Lead",
    date: "May 2026 — Present",
    current: true,
    field: "TRACE SUBTEAM / AGENT RELIABILITY",
    intro: "At Wat.ai, I built deterministic checks for agent reliability: comparing claims with retrieved evidence and checking that actions stayed within policy.",
    bullets: [
      "Architected TRACE’s deterministic agent-evaluation layer by defining Pydantic verifier contracts for pass/fail, evidence, severity, and affected trace steps across attribution, regression testing, and release gates.",
      "Achieved 100% evaluation accuracy across a 25-task policy suite by validating agent execution traces against retrieved documents, expected actions, tool side effects, and final state to detect unsafe or ungrounded behavior.",
      "Built agent guardrail evaluations measuring replay reliability and classifying recovery into six outcome categories.",
    ],
  },
  {
    slug: "manulife",
    company: "Manulife",
    role: "Software Engineering Intern",
    date: "Jan 2026 — Apr 2026",
    field: "FINANCIAL CORPORATION / ENTERPRISE SYSTEMS",
    intro: "At Manulife, I built data and telemetry pipelines that helped surface resource bottlenecks before service degradation. This example shows how an early-warning dashboard can make those signals visible.",
    bullets: [
      "Processed over 500,000 Salesforce records per export by building a scalable Python pipeline with Redis caching to extract, transform, and adapt application data into downstream-compatible formats.",
      "Reduced system downtime risk by building a New Relic telemetry exporter and SQL-based monitoring pipeline, enabling early detection of more than three resource bottlenecks before service degradation.",
    ],
  },
  {
    slug: "waterloo-aerial-robotics",
    company: "Waterloo Aerial Robotics Group",
    role: "Autonomy Software Developer",
    date: "Sep 2025 — Feb 2026",
    field: "AUTONOMY / COMPUTER VISION",
    bullets: [
      "Improved real-time autonomous UAV signal detection accuracy by 13% with OpenCV algorithms, iterative parameter tuning, and extensive flight simulation validation.",
      "Built multi-process telemetry and command systems in Python using PyMAVLink, reducing message latency by 30% across distributed processes.",
    ],
  },
  {
    slug: "c2c-development",
    company: "C2C Development Holdings",
    role: "Computer Support Specialist",
    date: "May 2022 — Sep 2025",
    field: "AUTOMATION / TECHNICAL SUPPORT",
    bullets: [
      "Engineered a Python bot that automated over 700 Facebook Marketplace customer interactions and improved response time by over 70%.",
      "Provided technical support in database management, hardware setup, and network troubleshooting.",
    ],
  },
  {
    slug: "custom-keyboards",
    company: "Custom Gaming Keyboards",
    role: "Founder & Operator",
    date: "Sep 2022 — Present",
    current: true,
    field: "HARDWARE / INDEPENDENT BUSINESS",
    bullets: [
      "Designed and sold over 35 custom keyboards, generating more than $5,500 in revenue.",
      "Built and maintained an e-commerce platform for orders, client communication, and margin optimization.",
    ],
  },
  {
    slug: "frc-8089",
    company: "FRC Team 8089",
    role: "Build & Design Team Planner",
    date: "High School",
    field: "ROBOTICS / ELECTRICAL ENGINEERING",
    bullets: [
      "Planned and designed electrical engineering components and constrained the robot’s physical build process.",
      "Collaborated with design and build sub-teams to define functional boundaries and integrate electronics efficiently.",
    ],
  },
];

export const stack = {
  Languages: [
    "Python",
    "Java",
    "C",
    "C++",
    "Swift",
    "TypeScript",
    "JavaScript",
    "SQL",
    "Apex",
    "HTML",
    "CSS",
    "VBA",
  ],
  "Frameworks & libraries": [
    "PyTorch",
    "TensorFlow",
    "scikit-learn",
    "RAG",
    "Pydantic",
    "React",
    "Node.js",
    "Flask",
    "Django",
    "FastAPI",
    "Next.js",
    "Spring",
    "Redis",
    "ROS 2",
    "MuJoCo",
    "Stable-Baselines3",
    "OpenCV",
    "REST APIs",
    "PyMAVLink",
    "NumPy",
    "JUnit",
    "Mockito",
    "Dagger",
    "LWC",
  ],
  "Tools & infrastructure": [
    "AWS · CDK / ECS / Lambda / S3 / SQS / SNS",
    "Git",
    "GitHub",
    "Docker",
    "Linux",
    "Kubernetes",
    "Salesforce",
    "New Relic",
    "VS Code",
    "Postman",
    "Xcode",
    "MongoDB",
    "SQL",
    "Raspberry Pi",
    "Arduino",
  ],
};

export const awards = [
  ["01", "Hack Canada 2026", "1st · Reactiv Track · $5,000"],
  ["02", "Most Complex AI Hack", "Shortlisted · Hack Canada 2026"],
  ["03", "Amazon Robotics Hackathon", "1st place"],
  ["04", "Chess AI Bot", "Bronze · Waterloo Tech Week"],
  ["05", "Euclid Math Contest", "1st · School Medal"],
  ["06", "Governor General’s Academic Award", "Academic distinction"],
  ["07", "Valedictorian", "Academic distinction"],
  ["08", "Hack The North 2026", "Winner · DominIQ"],
];
